config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :connections
  get 'sessions/new'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'sessions/create'
  get 'signout', to: 'sessions#destroy', as: 'signout'

  root 'welcome#index'
  resources :bands
  resources :band_users
  resources :demo_links
  resources :demos
  resources :messages, only: [:index, :new, :create, :show, :destroy]
  resources :connections, only: [:create, :update, :delete]
  resources :interest_types
  resources :interests
  resources :interest_users
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resource :home, only: [:show]

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/band_user.rb
class BandUser < ActiveRecord::Base
end

app/controllers/band_users_controller.rb
class BandUsersController < ApplicationController
  before_action :set_band_user, only: [:show, :edit, :update, :destroy]
  before_filter :restrict_access

  # GET /band_users
  # GET /band_users.json
  def index
    @band_users = BandUser.all
  end

  # GET /band_users/1
  # GET /band_users/1.json
  def show
  end

  # GET /band_users/new
  def new
    @band_user = BandUser.new
  end

  # GET /band_users/1/edit
  def edit
  end

  # POST /band_users
  # POST /band_users.json
  def create
    @band_user = BandUser.new(band_user_params)

    respond_to do |format|
      if @band_user.save
        format.html { redirect_to @band_user, notice: 'Band user was successfully created.' }
        format.json { render :show, status: :created, location: @band_user }
      else
        format.html { render :new }
        format.json { render json: @band_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /band_users/1
  # PATCH/PUT /band_users/1.json
  def update
    respond_to do |format|
      if @band_user.update(band_user_params)
        format.html { redirect_to @band_user, notice: 'Band user was successfully updated.' }
        format.json { render :show, status: :ok, location: @band_user }
      else
        format.html { render :edit }
        format.json { render json: @band_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /band_users/1
  # DELETE /band_users/1.json
  def destroy
    @band_user.destroy
    respond_to do |format|
      format.html { redirect_to band_users_url, notice: 'Band user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_band_user
      @band_user = BandUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def band_user_params
      params.fetch(:band_user, {})
    end
end

app/helpers/band_users_helper.rb
module BandUsersHelper
end

app/views/band_users/_form.html.erb
<%= form_for(@band_user) do |f| %>
  <% if @band_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@band_user.errors.count, "error") %> prohibited this band_user from being saved:</h2>

      <ul>
      <% @band_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/band_users/edit.html.erb
<h1>Editing Band User</h1>

<%= render 'form' %>

<%= link_to 'Show', @band_user %> |
<%= link_to 'Back', band_users_path %>

app/views/band_users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Band Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @band_users.each do |band_user| %>
      <tr>
        <td><%= link_to 'Show', band_user %></td>
        <td><%= link_to 'Edit', edit_band_user_path(band_user) %></td>
        <td><%= link_to 'Destroy', band_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Band user', new_band_user_path %>

app/views/band_users/new.html.erb
<h1>New Band User</h1>

<%= render 'form' %>

<%= link_to 'Back', band_users_path %>

app/views/band_users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_band_user_path(@band_user) %> |
<%= link_to 'Back', band_users_path %>