config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :connections
  get 'sessions/new'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'sessions/create'
  get 'signout', to: 'sessions#destroy', as: 'signout'

  root 'welcome#index'
  resources :bands
  resources :band_users
  resources :demo_links
  resources :demos
  resources :messages, only: [:index, :new, :create, :show, :destroy]
  resources :connections, only: [:create, :update, :delete]
  resources :interest_types
  resources :interests
  resources :interest_users
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resource :home, only: [:show]

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/demo_link.rb
class DemoLink < ActiveRecord::Base
end

app/controllers/demo_links_controller.rb
class DemoLinksController < ApplicationController
  before_action :set_demo_link, only: [:show, :edit, :update, :destroy]
  before_filter :restrict_access

  # GET /demo_links
  # GET /demo_links.json
  def index
    @demo_links = DemoLink.all
  end

  # GET /demo_links/1
  # GET /demo_links/1.json
  def show
  end

  # GET /demo_links/new
  def new
    @demo_link = DemoLink.new
  end

  # GET /demo_links/1/edit
  def edit
  end

  # POST /demo_links
  # POST /demo_links.json
  def create
    @demo_link = DemoLink.new(demo_link_params)

    respond_to do |format|
      if @demo_link.save
        format.html { redirect_to @demo_link, notice: 'Demo link was successfully created.' }
        format.json { render :show, status: :created, location: @demo_link }
      else
        format.html { render :new }
        format.json { render json: @demo_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /demo_links/1
  # PATCH/PUT /demo_links/1.json
  def update
    respond_to do |format|
      if @demo_link.update(demo_link_params)
        format.html { redirect_to @demo_link, notice: 'Demo link was successfully updated.' }
        format.json { render :show, status: :ok, location: @demo_link }
      else
        format.html { render :edit }
        format.json { render json: @demo_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /demo_links/1
  # DELETE /demo_links/1.json
  def destroy
    @demo_link.destroy
    respond_to do |format|
      format.html { redirect_to demo_links_url, notice: 'Demo link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_demo_link
      @demo_link = DemoLink.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def demo_link_params
      params.require(:demo_link).permit(:url, :description)
    end
end

app/helpers/demo_links_helper.rb
module DemoLinksHelper
end

app/views/demo_links/_form.html.erb
<%= form_for(@demo_link) do |f| %>
  <% if @demo_link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@demo_link.errors.count, "error") %> prohibited this demo_link from being saved:</h2>

      <ul>
      <% @demo_link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/demo_links/edit.html.erb
<h1>Editing Demo Link</h1>

<%= render 'form' %>

<%= link_to 'Show', @demo_link %> |
<%= link_to 'Back', demo_links_path %>

app/views/demo_links/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Demo Links</h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @demo_links.each do |demo_link| %>
      <tr>
        <td><%= demo_link.url %></td>
        <td><%= demo_link.description %></td>
        <td><%= link_to 'Show', demo_link %></td>
        <td><%= link_to 'Edit', edit_demo_link_path(demo_link) %></td>
        <td><%= link_to 'Destroy', demo_link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Demo link', new_demo_link_path %>

app/views/demo_links/new.html.erb
<h1>New Demo Link</h1>

<%= render 'form' %>

<%= link_to 'Back', demo_links_path %>

app/views/demo_links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @demo_link.url %>
</p>

<p>
  <strong>Description:</strong>
  <%= @demo_link.description %>
</p>

<%= link_to 'Edit', edit_demo_link_path(@demo_link) %> |
<%= link_to 'Back', demo_links_path %>